name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Ensure Haarcascade is present
        run: python download_haar.py

      - name: Install Cython and upgrade pip
        run: python -m pip install --upgrade pip cython

      - name: Build Kivy APK using Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: FaceApp-APK
          path: bin/*.apk
